### ISSUE TITLE
Not Working with mac M1 Max Chip

### ISSUE THREAD

**Issue by CodinSegal** [shader-park/shader-park-touchdesigner#4]
Hello guys,
First of all its an amazing tool, been using it on windows and had lots of fun with it. and very easy to use. Now I am trying to make it work with my mac and I get an error 
`shader-park-touchdesigner-master/dist/dist/shader-park-td-macos ; exit;
zsh: bad CPU type in executable: /Users/segalcodin/Documents/shader-park-touchdesigner-master/dist/dist/shader-park-td-macos

Saving session...completed.

[Process completed]

`

Do you guys have an idea how to make it work ?

**Comment by torinmb** [comment]
There's a brand new plugin that doesn't require building node which should fix this
